<script lang="ts">
  import { onMount } from 'svelte';
  import { api, apiError } from '$lib/api';
  type Identity = { id:string; object_class:string; display_name?:string; familiarity_score:number; familiarity:string; first_seen:string; last_seen:string; sightings:number };
  type History = { id:string; track_id:string; camera_id:string; similarity:number; observed_at:string };
  let identities: Identity[] = []; let selected: Identity | null = null; let history: History[] = []; let name = ''; let message = '';
  async function load() { const response = await api('/api/identities?limit=100'); if (response.ok) identities = await response.json(); }
  async function choose(identity: Identity) { selected = identity; name = identity.display_name ?? ''; const response = await api(`/api/identities/${identity.id}/history?limit=30`); if (response.ok) history = await response.json(); }
  async function rename() { if (!selected) return; const response = await api(`/api/identities/${selected.id}`, { method:'PUT', json:{display_name:name.trim() || null} }); message = response.ok ? 'Identity name saved' : await apiError(response); await load(); if (selected) selected = identities.find((item) => item.id === selected?.id) ?? selected; }
  onMount(load);
</script>
<svelte:head><title>Identities · Objexel</title></svelte:head>
<div class="row"><div><p class="eyebrow">Persistent recognition</p><h1>Identities</h1><p class="muted">Recurring animals, vehicles, and people become familiar objects instead of anonymous tracks.</p></div><span class="pill">{identities.length} identities</span></div>
{#if message}<p class="pill">{message}</p>{/if}
<div class="layout"><section class="card"><div class="row"><h2>Known objects</h2><span class="muted">Newest sighting</span></div>{#if identities.length === 0}<div class="empty">No identities learned yet. Process a few camera tracks to begin.</div>{:else}<div class="identity-list">{#each identities as identity}<button class:active={selected?.id === identity.id} on:click={() => choose(identity)}><div><strong>{identity.display_name ?? `${identity.object_class} · ${identity.id.slice(0,8)}`}</strong><small>{identity.object_class} · {identity.sightings} sightings</small></div><span class="pill">{identity.familiarity.replace('_',' ')}</span></button>{/each}</div>{/if}</section>
<aside>{#if selected}<div class="card"><p class="eyebrow">Identity profile</p><h2>{selected.display_name ?? 'Unnamed object'}</h2><p class="muted">{selected.object_class} · first seen {new Date(selected.first_seen).toLocaleDateString()}</p><div class="metric">{Math.round(selected.familiarity_score * 100)}%</div><p class="muted">Familiarity score · {selected.sightings} sightings</p><label>Display name<input bind:value={name} placeholder="e.g. Neighbour Cat" /></label><button class="save" on:click={rename}>Save name</button></div><div class="card"><h2>History</h2>{#if history.length === 0}<div class="empty">No linked sightings.</div>{:else}{#each history as item}<div class="history"><span class="pill">{Math.round(item.similarity * 100)}% match</span><span class="muted">{new Date(item.observed_at).toLocaleString()}</span></div>{/each}{/if}</div>{:else}<div class="card empty">Select an identity to inspect sightings and rename it.</div>{/if}</aside></div>
<style>
  h2{margin:0 0 6px}.layout{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(300px,.8fr);gap:20px;margin-top:30px}.identity-list{display:grid;gap:8px;margin-top:18px}.identity-list button{display:flex;justify-content:space-between;align-items:center;text-align:left;background:#0f1922;color:#e7edf5;border:1px solid #223342;border-radius:9px;padding:15px;cursor:pointer}.identity-list button:hover,.identity-list button.active{border-color:#74e0b4;background:#14252a}.identity-list small{display:block;color:#8293a4;margin-top:5px}.identity-list .pill{white-space:nowrap}label{display:grid;gap:7px;color:#8293a4;font-size:.8rem;margin-top:20px}input{background:#0b1017;border:1px solid #355164;border-radius:6px;padding:10px;color:#e7edf5}.save{margin-top:12px;background:#74e0b4;color:#0b1017;border:0;border-radius:6px;padding:10px 14px;font-weight:700}.history{display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid #223342}.history:last-child{border:0}.card+.card{margin-top:20px}@media(max-width:800px){.layout{grid-template-columns:1fr}}
</style>
