<script lang="ts">
  import { onMount } from 'svelte';
  import { api, apiError } from '$lib/api';
  type Action = { id:string; name:string; action_type:string; enabled:boolean; provider_id?:string };
  type Provider = { id:string; provider_type:string; enabled:boolean };
  let actions: Action[] = []; let providers: Provider[] = []; let name = ''; let providerType = 'internal'; let configuration = '{}'; let message = '';
  async function load() { const [a, p] = await Promise.all([api('/api/actions'), api('/api/notification-providers')]); if (a.ok) actions = await a.json(); if (p.ok) providers = await p.json(); }
  async function createProvider() { let parsed: unknown; try { parsed = JSON.parse(configuration); } catch { message = 'Configuration must be valid JSON'; return; } const response = await api('/api/notification-providers', { method:'POST', json:{ provider_type:providerType, enabled:true, configuration:parsed } }); message = response.ok ? 'Provider created' : await apiError(response); await load(); }
  async function createAction() { const provider = providers.find((item) => item.provider_type === providerType); const response = await api('/api/actions', { method:'POST', json:{ name, action_type:providerType, provider_id:provider?.id ?? null, enabled:true, configuration:{} } }); message = response.ok ? 'Action created' : await apiError(response); if (response.ok) name = ''; await load(); }
  async function toggleAction(action: Action) { const response = await api(`/api/actions/${action.id}`, { method:'PUT', json:{ enabled:!action.enabled } }); message = response.ok ? `${action.name} ${action.enabled ? 'disabled' : 'enabled'}` : await apiError(response); await load(); }
  async function removeAction(action: Action) { if (!confirm(`Delete action "${action.name}"?`)) return; const response = await api(`/api/actions/${action.id}`, { method:'DELETE' }); message = response.ok ? `${action.name} deleted` : await apiError(response); if (response.ok) await load(); }
  async function toggleProvider(provider: Provider) { const response = await api(`/api/notification-providers/${provider.id}`, { method:'PUT', json:{ enabled:!provider.enabled } }); message = response.ok ? `Provider ${provider.enabled ? 'disabled' : 'enabled'}` : await apiError(response); await load(); }
  async function testProvider(provider: Provider) { message = 'Sending test notification…'; const response = await api('/api/test-notification', { method:'POST', json:{ provider_id:provider.id } }); message = response.ok ? 'Test notification sent' : await apiError(response); }
  onMount(load);
</script>
<svelte:head><title>Actions · Objexel</title></svelte:head>
<p class="eyebrow">Response automation</p><h1>Actions</h1><p class="muted">Connect rule events to delivery providers. Provider credentials remain in PostgreSQL configuration and are never logged.</p>
{#if message}<p class="pill">{message}</p>{/if}
<section class="card form"><input bind:value={name} placeholder="Action name" /><select bind:value={providerType}><option value="internal">Internal</option><option value="email">Email</option><option value="webhook">Webhook</option><option value="mqtt">MQTT</option></select><textarea bind:value={configuration} placeholder="Provider JSON, e.g. a webhook URL"></textarea><button on:click={createProvider}>Create provider</button><button on:click={createAction} disabled={!name}>Create action</button></section>

{#if providers.length}<section class="card section"><h2>Providers</h2>{#each providers as provider}<div class="line"><div><strong>{provider.provider_type}</strong><small class="muted">{provider.id.slice(0,8)}</small></div><span class="pill" class:off={!provider.enabled}>{provider.enabled ? 'Enabled' : 'Disabled'}</span><div class="line-actions"><button on:click={() => testProvider(provider)}>Send test</button><button class="ghost" on:click={() => toggleProvider(provider)}>{provider.enabled ? 'Disable' : 'Enable'}</button></div></div>{/each}</section>{/if}

<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(280px,1fr));margin-top:24px">{#each actions as action}<article class="card"><div class="row"><strong>{action.name}</strong><span class="pill" class:off={!action.enabled}>{action.enabled ? 'Enabled' : 'Disabled'}</span></div><p class="muted">{action.action_type} · {action.provider_id ? action.provider_id.slice(0,8) : 'no provider'}</p><div class="line-actions"><button class="ghost" on:click={() => toggleAction(action)}>{action.enabled ? 'Disable' : 'Enable'}</button><button class="danger" on:click={() => removeAction(action)}>Delete</button></div></article>{/each}</div>
<style>.form{display:flex;gap:8px;flex-wrap:wrap;margin-top:28px}.form input,.form select,.form textarea{background:#0b1017;color:#e7edf5;border:1px solid #355164;border-radius:6px;padding:10px}.form input{flex:1;min-width:180px}.form textarea{min-width:260px;min-height:44px}.form button{border:0;border-radius:6px;padding:10px 12px;background:#74e0b4;color:#0b1017;font-weight:700}.section{margin-top:24px}.section h2{margin:0 0 12px}.line{display:flex;align-items:center;gap:14px;padding:12px 0;border-bottom:1px solid #223342}.line>div:first-child{flex:1}.line small{display:block;margin-top:3px}.pill.off{background:#3b2d1d;color:#f0c56d}.line-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.line-actions button{border:1px solid #355164;border-radius:6px;background:#162532;color:#dce8f1;padding:7px 10px;font-size:.8rem}.line-actions button.ghost{background:transparent}.line-actions button.danger{border-color:#6d2a35;color:#f0788a}.line .line-actions{margin-top:0}</style>
