[package]
name = "objexel-database"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
objexel-common = { path = "../common" }
objexel-analytics = { path = "../analytics" }
objexel-search = { path = "../search" }
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
uuid.workspace = true
