<script lang="ts">
  import { onMount } from 'svelte';
  type Model = { id:string; name:string; version:string; model_type:string; path:string; input_width:number; input_height:number; class_list:string[]; enabled:boolean; default_model:boolean };
  type Benchmark = { model_id:string; fps:number; average_inference_time_ms:number; gpu_memory_usage_mb?:number; test_timestamp:string };
  let models: Model[] = []; let benchmarks: Benchmark[] = []; let message = '';
  async function load() { const [modelResponse, benchmarkResponse] = await Promise.all([fetch('/api/models'), fetch('/api/benchmarks')]); if (modelResponse.ok) models = await modelResponse.json(); if (benchmarkResponse.ok) benchmarks = await benchmarkResponse.json(); }
  async function activate(id:string) { const response = await fetch(`/api/models/${id}/activate`, { method:'POST' }); message = response.ok ? 'Model activated' : await response.text(); await load(); }
  async function benchmark(id:string) { message = 'Benchmarking…'; const response = await fetch(`/api/models/${id}/benchmark`, { method:'POST' }); message = response.ok ? 'Benchmark complete' : await response.text(); await load(); }
  async function reload() { message = 'Reloading ONNX sessions…'; const response = await fetch('/api/models/reload', { method:'POST' }); message = response.ok ? 'Loaded models from the registry' : await response.text(); await load(); }
  onMount(load);
</script>
<svelte:head><title>Models · Objexel</title></svelte:head>
<div class="row"><div><p class="eyebrow">Inference control</p><h1>Models</h1><p class="muted">Manage interchangeable ONNX detectors and compare runtime performance.</p></div><button class="reload" on:click={reload}>Reload registry</button></div><div class="card model-note"><strong>Manual model installation</strong><p class="muted">Place trusted <code>.onnx</code> files in the mounted models directory, then reload the registry. Objexel does not download models automatically yet.</p></div>{#if message}<p class="pill">{message}</p>{/if}<div class="profiles"><span>Fast · low latency</span><span>Balanced · default</span><span>Accurate · high recall</span></div>
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr));margin-top:32px">{#each models as model}<article class="card"><div class="row"><div><h2>{model.name}</h2><p class="muted">{model.version} · {model.model_type}</p></div>{#if model.default_model}<span class="pill">Active</span>{/if}</div><p class="muted">{model.input_width} × {model.input_height} · {model.class_list.length} classes</p><small class="muted">{model.path}</small><div class="actions"><button on:click={() => activate(model.id)} disabled={model.default_model}>Activate</button><button on:click={() => benchmark(model.id)}>Benchmark</button></div>{#if benchmarks.find((item) => item.model_id === model.id)}{@const result = benchmarks.find((item) => item.model_id === model.id)}<div class="benchmark"><strong>{result?.fps.toFixed(1)} FPS</strong><span>{result?.average_inference_time_ms.toFixed(1)} ms average</span></div>{/if}</article>{/each}</div>
<style>h2{margin:0 0 4px}.model-note{margin-top:20px;border-color:#355164}.model-note p{margin:8px 0 0}.model-note code{color:#b9f2d5}.reload{background:#74e0b4;color:#0b1017;border:0;border-radius:6px;padding:10px 14px;font-weight:700}.profiles{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.profiles span{border:1px solid #294050;border-radius:99px;padding:7px 11px;color:#8293a4;font-size:.78rem}.actions{display:flex;gap:8px;margin-top:18px}.actions button{padding:8px 12px;border-radius:6px;border:1px solid #355164;background:#162532;color:#dce8f1}.actions button:first-child{background:#74e0b4;color:#0b1017;border-color:#74e0b4}.benchmark{display:flex;justify-content:space-between;border-top:1px solid #223342;margin-top:18px;padding-top:14px;color:#74e0b4}.benchmark span{color:#8293a4;font-size:.8rem}@media(max-width:600px){.row{align-items:flex-start;flex-direction:column}.reload{align-self:flex-start}}</style>
