<script lang="ts">
  import { onMount } from 'svelte';
  type Model = { id:string; name:string; version:string; model_type:string; path:string; input_width:number; input_height:number; class_list:string[]; enabled:boolean; default_model:boolean };
  type Benchmark = { model_id:string; fps:number; average_inference_time_ms:number; gpu_memory_usage_mb?:number; test_timestamp:string };
  type CatalogEntry = { id:string; name:string; version:string; model_type:string; download_url:string; sha256:string; input_width:number; input_height:number; class_list:string[]; archive_format?:string };
  type Download = { id:string; catalog_id:string; status:string; progress_percent:number; bytes_downloaded:number; total_bytes?:number; error?:string; model_id?:string };
  let models: Model[] = []; let catalog: CatalogEntry[] = []; let downloads: Download[] = []; let benchmarks: Benchmark[] = []; let message = '';
  async function load() {
    const [modelResponse, benchmarkResponse, catalogResponse] = await Promise.all([fetch('/api/models'), fetch('/api/benchmarks'), fetch('/api/models/catalog')]);
    if (modelResponse.ok) models = await modelResponse.json(); if (benchmarkResponse.ok) benchmarks = await benchmarkResponse.json(); if (catalogResponse.ok) catalog = await catalogResponse.json();
  }
  async function refreshDownloads() { for (const download of downloads.filter((item) => item.status === 'queued' || item.status === 'downloading')) { const response = await fetch(`/api/models/downloads/${download.id}`); if (response.ok) Object.assign(download, await response.json()); } downloads = downloads; }
  async function download(entry: CatalogEntry) { const response = await fetch(`/api/models/catalog/${entry.id}/download`, { method:'POST' }); if (!response.ok) { message = await response.text(); return; } downloads = [...downloads, await response.json()]; message = `Downloading ${entry.name} ${entry.version}…`; }
  async function toggle(model: Model) { const response = await fetch(`/api/models/${model.id}`, { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({enabled:!model.enabled}) }); message = response.ok ? `${model.name} ${model.enabled ? 'disabled' : 'enabled'}` : await response.text(); await load(); }
  async function activate(id:string) { const response = await fetch(`/api/models/${id}/activate`, { method:'POST' }); message = response.ok ? 'Model activated' : await response.text(); await load(); }
  async function benchmark(id:string) { message = 'Benchmarking…'; const response = await fetch(`/api/models/${id}/benchmark`, { method:'POST' }); message = response.ok ? 'Benchmark complete' : await response.text(); await load(); }
  async function reload() { message = 'Reloading ONNX sessions…'; const response = await fetch('/api/models/reload', { method:'POST' }); message = response.ok ? 'Loaded enabled models' : await response.text(); await load(); }
  onMount(() => { load(); const timer = window.setInterval(refreshDownloads, 1500); return () => window.clearInterval(timer); });
</script>

<svelte:head><title>Models · Objexel</title></svelte:head>
<div class="row"><div><p class="eyebrow">Inference control</p><h1>Models</h1><p class="muted">Install verified ONNX detectors, manage versions, and compare runtime performance.</p></div><button class="reload" on:click={reload}>Reload sessions</button></div>
{#if message}<p class="pill status">{message}</p>{/if}
<section class="card catalog"><div class="row"><div><h2>Verified catalog</h2><p class="muted">Downloads are checksum-verified before they become selectable models.</p></div><span class="pill">{catalog.length} available</span></div>{#if catalog.length === 0}<div class="empty">No catalog entries are configured. Administrators can still register trusted local ONNX files below.</div>{:else}<div class="catalog-grid">{#each catalog as entry}<article><div><strong>{entry.name}</strong><span class="muted">{entry.version} · {entry.model_type}</span></div><small class="muted">{entry.class_list.length} labels · SHA-256 verified</small><button on:click={() => download(entry)} disabled={downloads.some((item) => item.catalog_id === entry.id && ['queued','downloading'].includes(item.status))}>Download</button></article>{/each}</div>{/if}{#if downloads.length}<div class="downloads">{#each downloads as item}<div class="download-row"><span>{catalog.find((entry) => entry.id === item.catalog_id)?.name ?? item.catalog_id}</span><span class="muted">{item.status === 'failed' ? item.error : `${item.progress_percent}% · ${item.status}`}</span></div>{/each}</div>{/if}</section>
<div class="card model-note"><strong>Local models</strong><p class="muted">Place trusted <code>.onnx</code> files in the mounted models directory, register them with the API, then reload sessions. Catalog downloads are kept disabled until you explicitly enable them.</p></div>
<div class="profiles"><span>Fast · low latency</span><span>Balanced · default</span><span>Accurate · high recall</span></div>
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr));margin-top:32px">{#each models as model}<article class="card"><div class="row"><div><h2>{model.name}</h2><p class="muted">{model.version} · {model.model_type}</p></div>{#if model.default_model}<span class="pill">Active</span>{:else if !model.enabled}<span class="pill disabled">Disabled</span>{/if}</div><p class="muted">{model.input_width} × {model.input_height} · {model.class_list.length} classes</p><small class="muted">{model.path}</small><div class="actions"><button on:click={() => activate(model.id)} disabled={model.default_model || !model.enabled}>Activate</button><button on:click={() => toggle(model)}>{model.enabled ? 'Disable' : 'Enable'}</button><button on:click={() => benchmark(model.id)} disabled={!model.enabled}>Benchmark</button></div>{#if benchmarks.find((item) => item.model_id === model.id)}{@const result = benchmarks.find((item) => item.model_id === model.id)}<div class="benchmark"><strong>{result?.fps.toFixed(1)} FPS</strong><span>{result?.average_inference_time_ms.toFixed(1)} ms average</span></div>{/if}</article>{/each}</div>
<style>h2{margin:0 0 4px}.status{display:inline-block;margin-top:20px}.catalog{margin-top:20px;border-color:#355164}.catalog h2{margin:0}.catalog-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:10px;margin-top:18px}.catalog-grid article{display:grid;gap:10px;padding:14px;background:#0f1922;border:1px solid #223342;border-radius:8px}.catalog-grid article span{display:block;margin-top:4px;font-size:.8rem}.catalog-grid button,.actions button{padding:8px 12px;border-radius:6px;border:1px solid #355164;background:#162532;color:#dce8f1}.catalog-grid button{justify-self:start;background:#74e0b4;color:#0b1017;border-color:#74e0b4}.downloads{display:grid;gap:6px;margin-top:18px;padding-top:14px;border-top:1px solid #223342}.download-row{display:flex;justify-content:space-between;gap:12px;font-size:.85rem}.model-note{margin-top:20px}.model-note p{margin:8px 0 0}.model-note code{color:#b9f2d5}.reload{background:#74e0b4;color:#0b1017;border:0;border-radius:6px;padding:10px 14px;font-weight:700}.profiles{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.profiles span{border:1px solid #294050;border-radius:99px;padding:7px 11px;color:#8293a4;font-size:.78rem}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.actions button:first-child{background:#74e0b4;color:#0b1017;border-color:#74e0b4}.pill.disabled{background:#3b2d1d;color:#f0c56d}.benchmark{display:flex;justify-content:space-between;border-top:1px solid #223342;margin-top:18px;padding-top:14px;color:#74e0b4}.benchmark span{color:#8293a4;font-size:.8rem}@media(max-width:600px){.row{align-items:flex-start;flex-direction:column}.reload{align-self:flex-start}.download-row{align-items:flex-start;flex-direction:column}}
</style>
