[package]
name = "objexel-pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
objexel-actions = { path = "../actions" }
objexel-behaviour = { path = "../behaviour" }
objexel-fusion = { path = "../fusion" }
chrono.workspace = true
objexel-common = { path = "../common" }
objexel-database = { path = "../database" }
objexel-recorder = { path = "../recorder" }
objexel-detector = { path = "../detector" }
objexel-observations = { path = "../observations" }
objexel-rules = { path = "../rules" }
objexel-tracker = { path = "../tracker" }
objexel-zones = { path = "../zones" }
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
