<script lang="ts">
  import { onMount } from 'svelte';
  type Result = { entity_type:string; id:string; camera_id:string; object_class?:string; summary:string; occurred_at:string; confidence?:number; clip_id?:string; snapshot_id?:string };
  let q = ''; let objectClass = ''; let entity = 'all'; let results: Result[] = []; let loading = false; let searched = false;
  async function search() { loading = true; searched = true; const params = new URLSearchParams(); if (q) params.set('q', q); if (objectClass) params.set('object_class', objectClass); params.set('limit', '100'); const path = entity === 'all' ? '/api/search' : `/api/search/${entity}`; const response = await fetch(`${path}?${params}`); if (response.ok) results = await response.json(); loading = false; }
  onMount(search);
</script>
<svelte:head><title>Search · Objexel</title></svelte:head>
<p class="eyebrow">Investigation workspace</p><h1>Search activity</h1><p class="muted">Find objects, observations, events, tracks, and recordings across every camera.</p>
<section class="card searchbar"><input bind:value={q} on:keydown={(event) => event.key === 'Enter' && search()} placeholder="Try “cat”, “driveway”, or “person entered”" /><input bind:value={objectClass} placeholder="Object class" /><select bind:value={entity}><option value="all">Everything</option><option value="detections">Detections</option><option value="events">Events</option><option value="observations">Observations</option><option value="tracks">Tracks</option><option value="recordings">Recordings</option></select><button on:click={search}>Search</button></section>
{#if loading}<div class="empty">Searching the intelligence archive…</div>{:else if searched && results.length === 0}<div class="empty">No matching activity found.</div>{:else}<div class="row result-head"><strong>{results.length} results</strong><span class="muted">Sorted by newest activity</span></div><div class="results">{#each results as result}<article class="card result"><div class="row"><span class="pill">{result.entity_type}</span><small class="muted">{new Date(result.occurred_at).toLocaleString()}</small></div><h2>{result.summary}</h2><p class="muted">Camera {result.camera_id.slice(0,8)} {result.object_class ? `· ${result.object_class}` : ''}{result.confidence ? ` · ${Math.round(result.confidence * 100)}% confidence` : ''}</p><div class="links">{#if result.clip_id}<a href="/recordings">Open clip →</a>{/if}{#if result.snapshot_id}<a href="/recordings">View snapshot →</a>{/if}</div></article>{/each}</div>{/if}
<style>.searchbar{display:grid;grid-template-columns:minmax(220px,1fr) 150px 160px auto;gap:8px;margin-top:28px}.searchbar input,.searchbar select{background:#0b1017;color:#e7edf5;border:1px solid #355164;border-radius:6px;padding:11px}.searchbar button{border:0;border-radius:6px;padding:11px 18px;background:#74e0b4;color:#0b1017;font-weight:700}.result-head{margin:28px 0 12px}.results{display:grid;gap:10px}.result h2{font-size:1rem;margin:14px 0 4px}.result p{margin:0}.links{display:flex;gap:16px;margin-top:14px}.links a{color:#74e0b4;text-decoration:none;font-size:.85rem}@media(max-width:760px){.searchbar{grid-template-columns:1fr}.result-head{align-items:flex-start;flex-direction:column}}
</style>
