<script lang="ts">
  import { onMount } from 'svelte';
  type Identity = { id:string; object_class:string; display_name?:string; familiarity:string; familiarity_score:number; sightings:number };
  type Anomaly = { id:string; identity_id?:string; behaviour_id?:string; anomaly_score:number; priority_score:number; priority:string; created_at:string };
  let identities: Identity[] = []; let anomalies: Anomaly[] = []; let loading = true;
  onMount(async () => { const response = await fetch('/api/intelligence'); if (response.ok) { const data = await response.json(); identities = data.identities; anomalies = data.anomalies; } loading = false; });
</script>
<svelte:head><title>Intelligence · Objexel</title></svelte:head>
<div class="row"><div><p class="eyebrow">Adaptive intelligence</p><h1>Is this normal?</h1><p class="muted">Objexel learns recurring activity and ranks what deserves your attention.</p></div><span class="pill">{anomalies.length} scored signals</span></div>
{#if loading}<div class="empty">Scoring historical activity…</div>{:else}<div class="metrics"><div class="card"><span class="muted">Familiar identities</span><div class="metric">{identities.filter((item) => item.familiarity !== 'new').length}</div><small>recurring objects</small></div><div class="card"><span class="muted">Unusual signals</span><div class="metric">{anomalies.filter((item) => item.anomaly_score >= .45).length}</div><small>above normal baseline</small></div><div class="card alert"><span class="muted">Highest priority</span><div class="metric">{anomalies[0]?.priority ?? 'none'}</div><small>adaptive ranking</small></div></div><div class="columns"><section class="card"><div class="row"><h2>Known objects</h2><a href="/identities">Manage identities →</a></div>{#if identities.length === 0}<div class="empty">No identities scored yet.</div>{:else}{#each identities.slice(0,8) as identity}<div class="identity"><div><strong>{identity.display_name ?? identity.object_class}</strong><small>{identity.sightings} sightings · {identity.familiarity.replace('_',' ')}</small></div><div class="score"><span style={`width:${identity.familiarity_score * 100}%`}></span></div></div>{/each}{/if}</section><section class="card"><div class="row"><h2>Anomaly timeline</h2><span class="muted">newest and highest ranked</span></div>{#if anomalies.length === 0}<div class="empty">No anomaly events yet.</div>{:else}{#each anomalies.slice(0,10) as anomaly}<article class="anomaly"><span class:high={anomaly.priority === 'high' || anomaly.priority === 'critical'} class="pill">{anomaly.priority}</span><div><strong>{Math.round(anomaly.anomaly_score * 100)}% unusual</strong><small>{new Date(anomaly.created_at).toLocaleString()}</small></div><b>{Math.round(anomaly.priority_score * 100)}</b></article>{/each}{/if}</section></div>{/if}
<style>h2{margin:0;font-size:1rem}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:32px 0}.metric{font-size:2.1rem;margin:8px 0}.card small{color:#71869b}.alert{border-color:#6d5631}.columns{display:grid;grid-template-columns:1fr 1fr;gap:16px}.row a{color:#74e0b4;text-decoration:none;font-size:.8rem}.identity{padding:15px 0;border-bottom:1px solid #223342}.identity:last-child{border:0}.identity small{display:block;margin-top:5px}.score{height:6px;background:#1c2b36;border-radius:5px;margin-top:12px;overflow:hidden}.score span{display:block;height:100%;background:#74e0b4}.anomaly{display:flex;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid #223342}.anomaly>div{flex:1}.anomaly small{display:block;margin-top:4px;color:#71869b}.anomaly b{color:#f0c674}.pill.high{background:#3a2421;color:#ff9c87}@media(max-width:700px){.metrics,.columns{grid-template-columns:1fr}}
</style>
