<script lang="ts">
  import { onMount } from 'svelte';
  type Rule = { id:string; name:string; description:string; enabled:boolean; severity:string; cooldown_seconds:number; conditions:{object_class?:string;zone_id?:string;observation_type?:string;behaviour_type?:string;minimum_duration_ms?:number}[] };
  let rules: Rule[] = []; let loading = true;
  onMount(async () => { try { const response = await fetch('/api/rules'); if (response.ok) rules = await response.json(); } finally { loading = false; } });
  async function toggle(rule: Rule) { await fetch(`/api/rules/${rule.id}`, { method:'PUT', headers:{'content-type':'application/json'}, body:JSON.stringify({ enabled:!rule.enabled }) }); rule.enabled = !rule.enabled; rules = rules; }
</script>
<svelte:head><title>Rules · Objexel</title></svelte:head>
<p class="eyebrow">Decision layer</p><h1>Rules</h1><p class="muted">Observations describe what happened. Rules decide whether it matters.</p>
{#if loading}<div class="empty">Loading rules…</div>{:else if rules.length === 0}<div class="empty">No rules configured. Add a rule for object, zone, confidence, or duration conditions.</div>{:else}<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(280px,1fr));margin-top:32px">{#each rules as rule}<article class="card"><div class="row"><div><h2>{rule.name}</h2><p class="muted">{rule.description || 'No description'}</p></div><button class:active={rule.enabled} class="toggle" on:click={() => toggle(rule)}>{rule.enabled ? 'Enabled' : 'Disabled'}</button></div><div class="rule-meta"><span class="pill">{rule.severity}</span><span>{rule.conditions.length} conditions</span><span>{rule.cooldown_seconds}s cooldown</span></div>{#each rule.conditions as condition}<div class="condition">{condition.object_class || 'any object'} · {condition.behaviour_type || condition.observation_type || 'any observation'}{#if condition.minimum_duration_ms} · {condition.minimum_duration_ms/1000}s minimum{/if}</div>{/each}</article>{/each}</div>{/if}
<style>h2{margin:0 0 5px}.toggle{border:1px solid #355164;border-radius:99px;background:transparent;color:#8293a4;padding:6px 10px}.toggle.active{background:#18352f;color:#74e0b4;border-color:#28624f}.rule-meta{display:flex;gap:10px;align-items:center;margin:20px 0;color:#8293a4;font-size:.8rem}.condition{padding:9px 0;border-top:1px solid #223342;color:#c8d4df;font-size:.85rem}</style>
