<script lang="ts">
  import { onMount } from 'svelte';
  type Metric = { label:string; count:number }; type Summary = { detections:number; events:number; observations:number; behaviours:number; top_objects:Metric[]; camera_activity:Metric[]; zone_activity:Metric[]; model_activity:Metric[]; detections_per_day:Metric[] };
  let summary: Summary = { detections:0, events:0, observations:0, behaviours:0, top_objects:[], camera_activity:[], zone_activity:[], model_activity:[], detections_per_day:[] }; let loading = true;
  onMount(async () => { const response = await fetch('/api/analytics'); if (response.ok) summary = await response.json(); loading = false; });
</script>
<svelte:head><title>Analytics · Objexel</title></svelte:head>
<p class="eyebrow">Operational intelligence</p><h1>Analytics</h1><p class="muted">Understand what your cameras are seeing and where activity concentrates.</p>
{#if loading}<div class="empty">Calculating activity metrics…</div>{:else}<div class="metrics"><div class="card"><span class="muted">Detections</span><div class="metric">{summary.detections.toLocaleString()}</div><small>all observed objects</small></div><div class="card"><span class="muted">Events</span><div class="metric">{summary.events.toLocaleString()}</div><small>rule-generated signals</small></div><div class="card"><span class="muted">Behaviours</span><div class="metric">{summary.behaviours.toLocaleString()}</div><small>classified activity patterns</small></div></div><div class="columns"><section class="card"><h2>Top objects</h2>{#if summary.top_objects.length === 0}<div class="empty">No detections yet.</div>{:else}{#each summary.top_objects as item}<div class="bar-row"><span>{item.label}</span><strong>{item.count}</strong><div class="bar"><i style={`width:${Math.min(100, item.count / Math.max(1, summary.top_objects[0].count) * 100)}%`}></i></div></div>{/each}{/if}</section><section class="card"><h2>Busiest cameras</h2>{#if summary.camera_activity.length === 0}<div class="empty">No camera activity yet.</div>{:else}{#each summary.camera_activity as item}<div class="bar-row"><span>{item.label}</span><strong>{item.count}</strong><div class="bar"><i style={`width:${Math.min(100, item.count / Math.max(1, summary.camera_activity[0].count) * 100)}%`}></i></div></div>{/each}{/if}</section><section class="card"><h2>Zone activity</h2>{#if summary.zone_activity.length === 0}<div class="empty">No zone activity yet.</div>{:else}{#each summary.zone_activity as item}<div class="bar-row"><span>{item.label}</span><strong>{item.count}</strong><div class="bar"><i style={`width:${Math.min(100, item.count / Math.max(1, summary.zone_activity[0].count) * 100)}%`}></i></div></div>{/each}{/if}</section></div><section class="card daily"><div class="row"><h2>Detections per day</h2><span class="muted">UTC</span></div><div class="sparkbars">{#each summary.detections_per_day as item}<div title={`${item.label}: ${item.count}`} style={`height:${Math.max(8, item.count / Math.max(1, Math.max(...summary.detections_per_day.map((entry) => entry.count))) * 100)}%`}></div>{/each}</div></section>{/if}
<style>h2{font-size:1rem;margin:0 0 20px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:32px 0}.metric{font-size:2.2rem}.card small{color:#71869b}.columns{display:grid;grid-template-columns:1fr 1fr;gap:16px}.bar-row{display:grid;grid-template-columns:1fr auto;gap:6px;margin:16px 0}.bar-row span{color:#b9c8d5}.bar{grid-column:1/-1;height:7px;background:#1b2a35;border-radius:9px;overflow:hidden}.bar i{display:block;height:100%;background:#74e0b4;border-radius:9px}.daily{margin-top:16px}.sparkbars{height:150px;display:flex;align-items:end;gap:5px;border-bottom:1px solid #294050;padding-top:20px}.sparkbars div{flex:1;min-width:4px;background:#74e0b4;border-radius:4px 4px 0 0;opacity:.85}@media(max-width:700px){.metrics,.columns{grid-template-columns:1fr}}
</style>
