<script lang="ts">
  import { onMount } from 'svelte';
  type Point = { x:number; y:number };
  type Zone = { id:string; name:string; colour:string; polygon_coordinates:Point[]; camera_id:string };
  let cameraId = ''; let name = 'Backyard'; let colour = '#74e0b4'; let points: Point[] = []; let zones: Zone[] = []; let message = '';
  let canvas: HTMLCanvasElement;
  function draw(event: MouseEvent) { const rect = canvas.getBoundingClientRect(); points = [...points, { x: Number(((event.clientX-rect.left)/rect.width).toFixed(4)), y: Number(((event.clientY-rect.top)/rect.height).toFixed(4)) }]; }
  async function save() { const response = await fetch('/api/zones', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({camera_id:cameraId,name,colour,polygon_coordinates:points,enabled:true}) }); message = response.ok ? 'Zone saved' : await response.text(); if (response.ok) { points=[]; await load(); } }
  async function load() { const response = await fetch('/api/zones'); if (response.ok) zones = await response.json(); }
  onMount(load);
</script>
<svelte:head><title>Zones · Objexel</title></svelte:head>
<p class="eyebrow">Spatial intelligence</p><h1>Zone editor</h1><p class="muted">Draw normalized polygons over a camera view. Objects crossing them become spatial observations.</p>
<div class="editor"><section class="card"><div class="toolbar"><input bind:value={cameraId} placeholder="Camera UUID" /><input bind:value={name} placeholder="Zone name" /><input type="color" bind:value={colour} /><button on:click={save} disabled={points.length < 3 || !cameraId}>Save zone</button></div><div class="canvas-wrap"><img src={cameraId ? `/api/cameras/${cameraId}/snapshot` : ''} alt="Live camera preview" /><canvas bind:this={canvas} on:click={draw}></canvas>{#each points as point, index}<span class="point" style={`left:${point.x*100}%;top:${point.y*100}%`}>{index+1}</span>{/each}</div><p class="muted">{points.length} points · click to add polygon vertices · points use 0–1 normalized coordinates</p>{#if message}<p class="pill">{message}</p>{/if}</section><aside class="card"><h2>Saved zones</h2>{#if zones.length === 0}<p class="muted">No zones yet.</p>{:else}{#each zones as zone}<div class="zone-row"><span class="swatch" style={`background:${zone.colour}`}></span><div><strong>{zone.name}</strong><small>{zone.polygon_coordinates.length} vertices</small></div></div>{/each}{/if}</aside></div>
<style>.editor{display:grid;grid-template-columns:1fr 280px;gap:20px;margin-top:32px}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.toolbar input:not([type=color]){flex:1;min-width:130px;background:#0b1017;border:1px solid #2a4050;border-radius:6px;color:#e7edf5;padding:10px}.toolbar button{background:#74e0b4;color:#0b1017;border:0;border-radius:6px;padding:0 14px;font-weight:700}.canvas-wrap{position:relative;aspect-ratio:16/9;background:#0b1017;overflow:hidden;border-radius:8px;border:1px solid #2a4050}.canvas-wrap img,.canvas-wrap canvas{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.canvas-wrap canvas{cursor:crosshair}.point{position:absolute;transform:translate(-50%,-50%);background:#74e0b4;color:#0b1017;border-radius:50%;width:22px;height:22px;text-align:center;line-height:22px;font-size:11px;font-weight:800;pointer-events:none}.zone-row{display:flex;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid #223342}.zone-row small{display:block;color:#8293a4;margin-top:4px}.swatch{width:12px;height:12px;border-radius:50%}@media(max-width:800px){.editor{grid-template-columns:1fr}}
</style>
